modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/Mrbysco/LoyaltyRewards/issues"
license = "MIT"

[[mods]]
modId = "loyaltyrewards"
version = "${file.jarVersion}"
displayName = "Loyalty Rewards"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/loyalty-rewards"
authors = "Mrbysco, ShyNieke, iskall85, DownWithTaxation"
credits = "Iskall85 for coming up with the original idea and DownWithTaxation for expanding on it"
description = '''
Rewards for playtime
'''

[[dependencies.loyaltyrewards]]
modId = "minecraft"
type = "REQUIRED"
versionRange = "[1.20.4,1.21)"
ordering = "NONE"
side = "BOTH"
[[dependencies.loyaltyrewards]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "[20.4.100-beta,)"
ordering = "NONE"
side = "BOTH"